title: tstrait manual
author: Daiki Tagami
copyright: "2023"
only_build_toc_files: true

repository:
  url: https://github.com/daikitag/tstrait
  branch: main
  path_to_book: docs

html:
  use_repository_button: true
  use_issues_button: true

bibtex_bibfiles:
    - references.bib

sphinx:
  extra_extensions:
  - sphinx.ext.autodoc
  - sphinx.ext.autosummary
  - sphinx.ext.todo
  - sphinx.ext.viewcode
  - jupyter_sphinx

  config:
    myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    
    todo_include_todos: true

    nitpicky: true
    
    autodoc_member_order: bysource

    bibtex_reference_style: author_year