# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Tstrait manual
author: Tskit Developers
copyright: "2023"
only_build_toc_files: true

## How can we create logo like tskit, tsinfer, tsdate, etc?
#logo: logo.svg

execute:
  execute_notebooks: cache

launch_buttons:
  binderhub_url: ""

repository:
  url: https://github.com/tskit-dev/tstrait
  branch: main
  path_to_book: docs

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

  # NOTE this gets replaced by the build infrastructure during deployment
  extra_navbar: __TSTRAIT_VERSION__
  extra_footer: __TSTRAIT_VERSION__

sphinx:
    extra_extensions:
    - sphinx.ext.autodoc
    - sphinx_autodoc_typehints
    - sphinx.ext.autosummary
    - sphinx.ext.todo
    - sphinx.ext.viewcode
    - sphinx.ext.intersphinx
    - sphinx_issues
    - IPython.sphinxext.ipython_console_highlighting

    config:
      html_theme: sphinx_book_theme
      pygments_style: monokai
      myst_enable_extensions:
      - colon_fence
      - deflist
      - dollarmath
      - substitution
      issues_github_path: tskit-dev/tstrait
      todo_include_todos: true
      intersphinx_mapping:
        python: ["https://docs.python.org/3/", null]
        tskit: ["https://tskit.dev/tskit/docs/stable/", null]
        tskit-tutorials: ["https://tskit.dev/tutorials/", null]
        msprime: ["https://tskit.dev/msprime/docs/stable/", null]
        stdpopsim: ["https://stdpopsim.readthedocs.io/en/stable", null]
        numpy: ["https://numpy.org/doc/stable/", null]

      autodoc_member_order: bysource

      # Without this option, autodoc tries to put links for all return types
      # in terms of the fully-qualified classnames which we don't want, and also
      # leads to broken links and nitpick failures. So, until we tackle
      # typehints fully, this is the simplest approach.
      autodoc_typehints: none
